import { Client, GatewayIntentBits, REST, Routes, SlashCommandBuilder, ChatInputCommandInteraction } from "discord.js";
import { config } from "dotenv";
import { Container, Section, ActionRow, Button, TextDisplay, Thumbnail, File, MediaGallery, MediaGalleryItem, parseColor, BuilderError } from "discord-container-kit";

config();

const TOKEN = process.env.DISCORD_TOKEN;
const CLIENT_ID = process.env.DISCORD_CLIENT_ID;

if (!TOKEN || !CLIENT_ID) {
  console.error("Missing DISCORD_TOKEN or DISCORD_CLIENT_ID in .env file.");
  process.exit(1);
}

const client = new Client({
  intents: [GatewayIntentBits.Guilds]
});

// Define commands
const commands = [
  new SlashCommandBuilder()
    .setName("showcase")
    .setDescription("Shows a complex Components V2 showcase"),
  new SlashCommandBuilder()
    .setName("debug-json")
    .setDescription("Shows the raw JSON payload generated by the builder"),
  new SlashCommandBuilder()
    .setName("validation")
    .setDescription("Demonstrates validation error handling")
].map(c => c.toJSON());

const rest = new REST({ version: "10" }).setToken(TOKEN);

client.once("ready", async () => {
  console.log(`Ready! Logged in as ${client.user?.tag}`);

  try {
    console.log("Started refreshing application (/) commands.");
    await rest.put(Routes.applicationCommands(CLIENT_ID), { body: commands });
    console.log("Successfully reloaded application (/) commands.");
  } catch (error) {
    console.error(error);
  }
});

client.on('interactionCreate', async interaction => {
  try {
    if (interaction.isButton()) {
      switch (interaction.customId) {
        case "btn_primary":
          await interaction.reply({ content: "✅ You clicked the Primary button!", ephemeral: true });
          break;
        case "btn_secondary":
          await interaction.reply({ content: "✅ You clicked the Secondary button!", ephemeral: true });
          break;
        case "btn_danger":
          await interaction.reply({ content: "🚨 You clicked the Danger button!", ephemeral: true });
          break;
        case "btn_features":
          await interaction.reply({ content: "✨ You clicked the Features Learn More button!", ephemeral: true });
          break;
        default:
          await interaction.reply({
            content: "⚠️ This interaction is not recognized by this version of the bot.",
            ephemeral: true
          });
      }
      return;
    }

    if (!interaction.isChatInputCommand()) return;

    switch (interaction.commandName) {
      case "showcase":
        await handleShowcase(interaction);
        break;
      case "debug-json":
        await handleDebugJson(interaction);
        break;
      case "validation":
        await handleValidation(interaction);
        break;
    }
  } catch (err) {
    console.error("Unhandled error in interactionCreate:", err);

    if (interaction.isRepliable()) {
      try {
        const payload = {
          content: "⚠️ Something went wrong while handling this interaction.",
          ephemeral: true
        };

        if (interaction.deferred || interaction.replied) {
          await interaction.followUp(payload);
        } else {
          await interaction.reply(payload);
        }
      } catch (replyErr) {
        console.error("Failed to send fallback reply:", replyErr);
      }
    }
  }
});

async function handleShowcase(interaction: ChatInputCommandInteraction) {
  const container = new Container()
    .accent(parseColor("#5865F2", "Showcase"))
    .add(
      new Section()
        .add(
          new TextDisplay().content("## Built with discord-container-kit"),
          new TextDisplay().content("Example of discord-container-kit usage.")
        )
        .accessory(new Thumbnail().url("https://discord.com/assets/2c21aeda16de354ba5334551a883b481.png")),
      new ActionRow()
        .add(
          new Button().link("https://github.com/demondevx/discord-container-kit", "GitHub Repo"),
          new Button().link("https://github.com/demondevx/discord-container-kit/tree/main/docs", "Documentation")
        )
    );

  await interaction.client.rest.post(Routes.interactionCallback(interaction.id, interaction.token), {
    body: {
      type: 4, 
      data: {
        flags: 32768,
        components: [container.toJSON()]
      }
    }
  });
}

async function handleDebugJson(interaction: ChatInputCommandInteraction) {
  const container = new Container()
    .accent("#FF0000")
    .add(
      new Section().add(new TextDisplay().content("Hello World!"))
    );

  const json = JSON.stringify(container.toJSON(), null, 2);

  await interaction.reply({
    content: `\`\`\`json\n${json}\n\`\`\``,
    ephemeral: true
  });
}

async function handleValidation(interaction: ChatInputCommandInteraction) {
  try {
    // Intentionally cause an error: ActionRow with 6 buttons (max is 5)
    new ActionRow().add(
      new Button().primary("1", "1"),
      new Button().primary("2", "2"),
      new Button().primary("3", "3"),
      new Button().primary("4", "4"),
      new Button().primary("5", "5"),
      new Button().primary("6", "6") // This will throw
    ).toJSON(); // toJSON triggers the validation

    await interaction.reply("If you see this, validation failed to throw!");
  } catch (error) {
    if (error instanceof BuilderError) {
      await interaction.reply({
        content: `**Validation Error Caught Successfully!**\n\n**Code:** \`${error.code}\`\n**Builder:** \`${error.builderName}\`\n**Message:** ${error.message}`,
        ephemeral: true
      });
    } else {
      throw error;
    }
  }
}

client.login(TOKEN);
